### PR TITLE
Square payment endpoint

### LINKED ISSUE #45: FIx admin order
Whenever a square payment method is present the admin payment page fails with:

Screenshot 2021-11-19 at 09 19 21

We have to add the the right partial.

In order to authorize the payment we should follow the square instruction https://developer.squareup.com/docs/web-payments/take-card-payment

### PR DESCRIPTION
**Pull request by garciajordy**
# Square Payment Endpoint

In order to fix this error, I had to add a partial to input the card details on the admin panel.

Square provides JavaScript to render the card input form and to convert that information into a nonce.

I created an endpoint that will retrieve this nonce and create a payment on square using that nonce, when the payment is successfully created on square, I use that response to create a payment on Solidus.

fix #45

### CODE REVIEW

File: app/services/solidus_square/payments/create.rb [hunk 1]
```diff
@@ -0,0 +1,42 @@
+# frozen_string_literal: true
+
+module SolidusSquare
+  module Payments
+    class Create < ::SolidusSquare::Base
+      attr_reader :client, :source_id, :amount, :auto_complete
```
Comment (DanielePalombo) [inline app/services/solidus_square/payments/create.rb:6]: Can you move the attr_reader under the private section?

File: app/services/solidus_square/payments/create.rb [hunk 2]
```diff
@@ -0,0 +1,42 @@
...
+
+      def payment_payload
+        {
+          idempotency_key: idempotency_key,
+          source_id: source_id,
+          amount_money: {
+            amount: amount,
+            currency: "USD"
+          },
+          autocomplete: auto_complete
```
Comment (DanielePalombo) [inline app/services/solidus_square/payments/create.rb:37]: autocomplete on square should be always false.

This is because even If `Spree::PaymentMethod#auto_capture?` is set to true, we'll capture the payment only when the order is completed.

File: app/services/solidus_square/create_payment_service.rb [hunk 3]
```diff
@@ -0,0 +1,67 @@
...
+    def call
+      order.next! if order.delivery?
+      complete_payment!
+    end
+
+    private
+
+    def complete_payment!
+      payment = create_payment!
+      payment.complete! if payment.source.captured?
```
Comment (DanielePalombo) [inline app/services/solidus_square/create_payment_service.rb:24]: It won't happen because the payment will be captured only after order complete.

File: app/services/solidus_square/create_payment_service.rb [hunk 4]
```diff
@@ -0,0 +1,67 @@
...
+      @gateway ||= payment_method.gateway
+    end
+
+    def payment_amount
+      square_payment_response[:amount_money][:amount] / 100.0
+    end
+
+    def square_order_total
+      (order.total * 100).to_i
+    end
```
Comment (DanielePalombo) [inline app/services/solidus_square/create_payment_service.rb:59]: What do you think to move the conversion from decimal to cents into the `SolidusSquare::Payments::Create`

File: spec/services/solidus_square/create_payment_service_spec.rb [hunk 5]
```diff
@@ -0,0 +1,81 @@
...
+      amount_money: {
+        amount: order.total
+      },
+      card_details: {
+        status: status,
+        card: {
+          card_brand: "MASTERCARD",
+          # rubocop:disable Naming/VariableNumber
+          last_4: "9029",
+          # rubocop:enable Naming/VariableNumber
```
Comment (DanielePalombo) [inline spec/services/solidus_square/create_payment_service_spec.rb:25]: You can disable this cop in one line

File: spec/services/solidus_square/create_payment_service_spec.rb [hunk 6]
```diff
@@ -0,0 +1,81 @@
...
+        avs_status: "AVS_ACCEPTED",
+      },
+      order_id: 12,
+      version_token: 12_345
+    }
+  end
+
+  before do
+    allow(Spree::PaymentMethod).to receive(:find).and_return(payment_method)
+    allow(gateway).to receive(:create_payment).and_return(square_response)
```
Comment (DanielePalombo) [inline spec/services/solidus_square/create_payment_service_spec.rb:39]: You have missed the test for the parameters, and the test for this method:

https://github.com/nebulab/solidus_square/pull/49/commits/a3d3c036591ded5111759fa62cf01d55057cedf6#diff-00a6869703c8a39f974141b47b11dad1cb5940285bc866d9516e23e8dcb83495R57-R59

File: app/controllers/solidus_square/payments_controller.rb [hunk 7]
```diff
@@ -0,0 +1,26 @@
+# frozen_string_literal: true
+
+module SolidusSquare
+  class PaymentsController < BaseController
```
Comment (DanielePalombo) [inline app/controllers/solidus_square/payments_controller.rb:4]: This is an API endpoint, it should be under the API namespace, as the [Api::CheckoutController](https://github.com/nebulab/solidus_square/blob/main/app/controllers/solidus_square/api/checkout_controller.rb)

File: app/controllers/solidus_square/payments_controller.rb [hunk 8]
```diff
@@ -0,0 +1,26 @@
...
+    rescue StandardError => e
+      render json: { error: e.message }, status: :unprocessable_entity
+    end
+
+    private
+
+    def order_token
+      request.headers["X-Spree-Order-Token"]
+    end
+  end
```
Comment (DanielePalombo) [inline app/controllers/solidus_square/payments_controller.rb:25]: What do you think to reuse [that code](https://github.com/nebulab/solidus_square/blob/main/app/controllers/solidus_square/api/checkout_controller.rb#L24)?

File: config/routes.rb [hunk 9]
```diff
@@ -10,4 +10,6 @@
 
   # Uncomment this line to activate the endpoint for the Square order.updated Webhook
   # post "webhooks/square", to: '/solidus_square/webhooks#update'
+
+  post "payments/square", to: '/solidus_square/payments#create'
```
Comment (DanielePalombo) [inline config/routes.rb:14]: this should be under API path

File: spec/controllers/solidus_square/payments_controller_spec.rb [hunk 10]
```diff
@@ -0,0 +1,46 @@
...
+      {
+        payment: {
+          order_number: order.number
+        }
+      }
+    end
+
+    context "with valid params" do
+      before do
+        allow(SolidusSquare::CreatePaymentService).to receive(:call)
```
Comment (DanielePalombo) [inline spec/controllers/solidus_square/payments_controller_spec.rb:22]: When you stub something don't forget to test the parameters.

File: app/controllers/solidus_square/callback_actions_controller.rb [hunk 11]
```diff
@@ -8,12 +8,13 @@ class CallbackActionsController < BaseController
...
 
     def square_checkout
-      authorize! :update, @order, order_token
+      authorize! :update, @order, cookies.signed[:guest_token]
 
       checkout_page_url = helpers.solidus_square_gateway.checkout(@order, redirect_url)[:checkout_page_url]
 
       respond_to do |format|
         format.html { redirect_to checkout_page_url }
+        format.json { render json: { checkout_page_url: checkout_page_url } }
```
Comment (DanielePalombo) [inline app/controllers/solidus_square/callback_actions_controller.rb:17]: We have a [specific controller](https://github.com/nebulab/solidus_square/blob/main/app/controllers/solidus_square/api/checkout_controller.rb#L5) to respond to JSON. Why you have added it back here?

File: app/controllers/solidus_square/callback_actions_controller.rb [hunk 12]
```diff
@@ -25,16 +26,12 @@ def complete_checkout
...
-      request.headers["X-Spree-Order-Token"] || params[:order_token]
-    end
-
     def load_order
       @order = current_order
     end
 
     def redirect_url
-      square_checkout_complete_url
+      complete_checkout_url
```
Comment (DanielePalombo) [inline app/controllers/solidus_square/callback_actions_controller.rb:34]: nice catch

**Review by DanielePalombo — CHANGES_REQUESTED** [review]

File: app/assets/javascripts/solidus_square.js [hunk 13]
```diff
@@ -0,0 +1,131 @@
+let appId;
+let locationId;
+let orderNumber;
+let orderToken;
+
+document.addEventListener('DOMContentLoaded', async function () {
+  const checkoutPayload = document.getElementById(
+    'square-checkout-payload'
+  );
+  //squareCardButton.addEventListener('click', function () {
```
[the remark this answers is not in the document]
Comment (garciajordy) [reply app/assets/javascripts/solidus_square.js]: https://github.com/nebulab/solidus_square/pull/49/commits/408597646d0c9ce10c7980b537c6b57ea0393e2b

File: app/assets/javascripts/solidus_square.js [hunk 14]
```diff
@@ -0,0 +1,131 @@
...
+  return card;
+}
+// Call this function to send a payment token, buyer name, and other details
+// to the project server code so that a payment can be created with
+// Payments API
+async function createPayment(token) {
+  const body = JSON.stringify({
+    source_id: token,
+    order_number: orderNumber,
+    payment_method_id: $('[name="payment[payment_method_id]"]:checked').val()
```
[the remark this answers is not in the document]
Comment (garciajordy) [reply app/assets/javascripts/solidus_square.js]: https://github.com/nebulab/solidus_square/pull/49/commits/408597646d0c9ce10c7980b537c6b57ea0393e2b

File: app/services/solidus_square/payments/create.rb (hunk 1 above)
Comment (garciajordy) [reply app/services/solidus_square/payments/create.rb]: https://github.com/nebulab/solidus_square/pull/49/commits/6dcd98efc275d3b3cba8faae8338ec2231940fd9

File: app/services/solidus_square/create_payment_service.rb (hunk 3 above)
Comment (garciajordy) [reply app/services/solidus_square/create_payment_service.rb]: https://github.com/nebulab/solidus_square/pull/49/commits/895e71c2f8fa90e07e6277827b947919170b1292

File: app/controllers/solidus_square/payments_controller.rb (hunk 8 above)
Comment (garciajordy) [reply app/controllers/solidus_square/payments_controller.rb]: https://github.com/nebulab/solidus_square/pull/49/commits/eef3bb8aadb12106067bcb45c5eced8524348bb8

File: config/routes.rb (hunk 9 above)
Comment (garciajordy) [reply config/routes.rb]: https://github.com/nebulab/solidus_square/pull/49/commits/b0dd811d394c6ce3eaf59f85907c46318ebb244d

File: spec/controllers/solidus_square/payments_controller_spec.rb (hunk 10 above)
Comment (garciajordy) [reply spec/controllers/solidus_square/payments_controller_spec.rb:25]: https://github.com/nebulab/solidus_square/pull/49/commits/b0dd811d394c6ce3eaf59f85907c46318ebb244d

File: app/controllers/solidus_square/callback_actions_controller.rb (hunk 11 above)
Comment (garciajordy) [reply app/controllers/solidus_square/callback_actions_controller.rb]: https://github.com/nebulab/solidus_square/pull/49/commits/930584fd6ac9faa791f751ac32ef34093bf43ee1

File: app/controllers/solidus_square/api/checkout_controller.rb [hunk 15]
```diff
@@ -2,7 +2,7 @@
 
 module SolidusSquare
   module Api
-    class CheckoutController < BaseController
+    class CheckoutController < ::SolidusSquare::BaseController
```
Comment (DanielePalombo) [inline app/controllers/solidus_square/api/checkout_controller.rb:5]: I'm curios,
BaseController is under SolidusSquare namespace, are you sure that you need to specify the parent namespace? 🤔

File: app/controllers/solidus_square/base_controller.rb [hunk 16]
```diff
@@ -9,6 +9,10 @@ class BaseController < ::Spree::BaseController
 
     private
 
+    def order_token
```
Comment (DanielePalombo) [inline app/controllers/solidus_square/base_controller.rb:12]: This method is only required by the API controllers.
What do you think to create a specific API BaseController where move it there, and let the API controllers inherit from it?

Comment (garciajordy) [reply app/controllers/solidus_square/base_controller.rb:12]: https://github.com/nebulab/solidus_square/pull/49/commits/591b5191d9fd9f444e56482bf3019ac8c5393bfb

File: app/controllers/solidus_square/api/checkout_controller.rb (hunk 15 above)
Comment (garciajordy) [reply app/controllers/solidus_square/api/checkout_controller.rb]: https://github.com/nebulab/solidus_square/pull/49/commits/591b5191d9fd9f444e56482bf3019ac8c5393bfb

File: spec/services/solidus_square/create_payment_service_spec.rb (hunk 5 above)
Comment (garciajordy) [reply spec/services/solidus_square/create_payment_service_spec.rb]: https://github.com/nebulab/solidus_square/pull/49/commits/4920d74201d57ea1ec93f607f0f37f2a740c634a

File: spec/services/solidus_square/create_payment_service_spec.rb (hunk 6 above)
Comment (garciajordy) [reply spec/services/solidus_square/create_payment_service_spec.rb:37]: https://github.com/nebulab/solidus_square/pull/49/commits/4920d74201d57ea1ec93f607f0f37f2a740c634a

File: app/services/solidus_square/create_payment_service.rb (hunk 4 above)
Comment (garciajordy) [reply app/services/solidus_square/create_payment_service.rb]: https://github.com/nebulab/solidus_square/pull/49/commits/47433f81b4e5d4331e2393b0dbf810e3f92b3bb3

**Review by DanielePalombo — APPROVED** [review]
